baseURL = "http://angelabennedsen.dk/hugoaflevering/"
languageCode = "en-us"
title = "ANGELA'S TRAVEL BLOG"
theme = "minimal"
publishDir = "docs"


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3
    
    [[menu.main]]
    url = "portfolio/"
    name = "Portfolio"
    weight = 4

